project_name        = "aws-prometheus-grafana-otel-collector-v1"
region              = "us-east-1"
aws_region          = "us-east-1"
environment         = "dev"
vpc_cidr            = "10.0.0.0/16"
availability_zones  = ["us-east-1a", "us-east-1b"]
domain_name         = "sreconcepts.com"
create_ssl_cert     = false
dockerhub_username  = "qaconcept" # used for 11-test-app which is optional.
